# Generated by Django 4.1.3 on 2023-05-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/%Y/%m/%d')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Imadmin.subject')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='files/%Y/%m/%d')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='Imadmin.subject')),
            ],
        ),
    ]
