# Generated by Django 4.1.3 on 2023-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
