# Generated by Django 4.1.3 on 2023-05-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Imadmin', '0002_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imadmin.subject'),
        ),
        migrations.AlterField(
            model_name='image',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imadmin.subject'),
        ),
    ]
