# Generated by Django 4.1.3 on 2023-06-09 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Imadmin', '0005_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
