# Generated by Django 4.1.3 on 2023-06-09 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Imadmin', '0006_announce_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='currentdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
